### ISSUE TITLE
Deployments do not get installed

### ISSUE THREAD

**Issue by rimusz** [helm/helm-classic#475] opened 2016-05-15 17:54 UTC
Made a chart with deployments and services, services get installed as usual, deployments spit the error:
```
error validating "STDIN": error validating data: API version "" isn't supported, only supports API versions ["componentconfig/v1alpha1" "batch/v1" "autoscaling/v1" "authorization.k8s.io/v1beta1" "v1" "metrics/v1alpha1" "extensions/v1beta1"]; if you choose to ignore these errors, turn validation off with --validate=false

```
Installing deployments manifest file via kubectl, everything works just fine.

**Comment by krancour** [comment] 2016-05-15 20:51
Duplicate of #456, which is already fixed in master.

**Closed by krancour** 2016-05-15 20:51 UTC
